### 基本語法

In [22]:
import numpy as np

a = np.array([100, True, 33.85, 28])#元素類型必須相同
print(a)

[100.     1.    33.85  28.  ]


Numpy API：https://numpy.org/doc/stable/reference/generated/numpy.array.html

In [23]:
import numpy as np

k1 = np.array([[5,10,15],
                    [2,4,6],
                    [1,3,5]])

k2 = np.array([100])

k3 = np.array([[100],
              [100],
              [100]])
print(k1)
print(k2)

[[ 5 10 15]
 [ 2  4  6]
 [ 1  3  5]]
[100]


In [24]:
print(k1+k2) # 廣播機制

[[105 110 115]
 [102 104 106]
 [101 103 105]]


In [25]:
#簡單計算

x = [10,20,30]
print(x+[40,50])#list 合併元素

y = np.array(x)
print(y+[40,50,60])#numpy會自動推播數量再進行計算

[10, 20, 30, 40, 50]
[50 70 90]


In [26]:
A = np.array([10,10,10])
print(type(A))
print(A+10)


<class 'numpy.ndarray'>
[20 20 20]


In [27]:
a4 = np.array([11,12,13,14,15,16])
a5 = np.array([[1,2,3,4],
               [11,12,13,14],
               [21,22,23,24]])
#結構
print(a4.shape)
print(a5.shape)

(6,)
(3, 4)


In [28]:
#改變結構
print(a4.reshape(2,3))
print(a4)
print('-------------------')

print(a4.reshape(3,-1))# -1代表自動調整計算
print(a4.reshape(-1,2))

print(a5.reshape(6,-1))# -1代表自動調整計算
print(a5.reshape(-1,12)) # -1代表自動調整計算

[[11 12 13]
 [14 15 16]]
[11 12 13 14 15 16]
-------------------
[[11 12]
 [13 14]
 [15 16]]
[[11 12]
 [13 14]
 [15 16]]
[[ 1  2]
 [ 3  4]
 [11 12]
 [13 14]
 [21 22]
 [23 24]]
[[ 1  2  3  4 11 12 13 14 21 22 23 24]]


In [29]:
#轉成一維
print(a5.reshape(-1))

[ 1  2  3  4 11 12 13 14 21 22 23 24]


In [30]:
#讀取元素
import numpy as np
x = np.array([[86,75,89],
              [77,62,81],
              [82,69,85]])
#指定單一位置，若位置不存在則出錯
print(x[0])
#print(x[5])
print(x[0][2]) # 第一列第三個元素
print(x[0,2]) # 第一列第三個元素

[86 75 89]
89
89


In [31]:
#slice 範圍選取，若位置不存在則返回[]
print(x)
print(x[:2])
print('----------------')
print(x[0][1:2])
print(x[0][1: ])
print(x[0][10:30])
print(x[0][:20])
print('----------------')
print(x[:])
print(x)
print('----------------')
print(x[0,0:2])
print(x[:2, 1:])

[[86 75 89]
 [77 62 81]
 [82 69 85]]
[[86 75 89]
 [77 62 81]]
----------------
[75]
[75 89]
[]
[86 75 89]
----------------
[[86 75 89]
 [77 62 81]
 [82 69 85]]
[[86 75 89]
 [77 62 81]
 [82 69 85]]
----------------
[86 75]
[[75 89]
 [62 81]]


In [32]:
# 亂數
np.random.seed(123)#固定亂數規則(基數)

arr0 = np.random.randint(0, 11)#0-11(有包含11)之間產生一個隨機整數
print(arr0)
arr00 = np.random.randint(0, 11, 3)#0-11(有包含11)之間產生3個隨機整數
print(arr00)

arr1 = np.random.randint(0, 11, (5, 2))
print('arr1:')
print(arr1)
print("-----------------------")
arr2 = np.random.rand(3)# 3個隨機小數，0-1之間(不含 1)
print('arr2:')
print(arr2)

2
[2 6 1]
arr1:
[[ 3 10]
 [ 9  6]
 [ 1  0]
 [ 1  9]
 [ 0  0]]
-----------------------
arr2:
[0.72904971 0.43857224 0.0596779 ]


In [33]:
np.random.seed(0)
x = ['蘋果', '橘子', '香蕉', '鳳梨', '奇異果', '草莓']
print(np.random.choice(x, 3))

['奇異果' '草莓' '蘋果']


In [34]:
# 條件套用
arr = np.arange(10)#產生0~9的整數

new_arr = arr%5==0
print(arr)
print(new_arr)
print(arr[new_arr])

[0 1 2 3 4 5 6 7 8 9]
[ True False False False False  True False False False False]
[0 5]


### 數學函式

In [35]:
arr = np.array([4, -9, 16, -4, 20])
print(arr)
arr_abs = np.abs(arr)
print('絕對值:',arr_abs)
print('e為底數:',np.exp(arr_abs))
print('平方根:',np.sqrt(arr_abs))

[ 4 -9 16 -4 20]
絕對值: [ 4  9 16  4 20]
e為底數: [5.45981500e+01 8.10308393e+03 8.88611052e+06 5.45981500e+01
 4.85165195e+08]
平方根: [2.         3.         4.         2.         4.47213595]


## 統計計算

In [36]:
b1 = np.array(np.arange(12).reshape(3,-1))
print(b1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [37]:
print(np.sum(b1))
print(np.sum(b1, axis=0))#垂直向下
print(np.sum(b1, axis=1))#水平向右

66
[12 15 18 21]
[ 6 22 38]


In [38]:
print(sum(b1))#python內建函式

[12 15 18 21]


In [39]:
print("垂直加總：",np.sum(b1, axis=0))
print("橫向加總：",np.sum(b1, axis=1))
print("------------------------------------")
print("加總：",b1.sum(axis=0))

print("平均：",np.mean(b1, axis=0))
print("中位數：",np.median(b1, axis=0))

print("變異數：",np.var(b1, axis=0))
print("標準差：",np.std(b1, axis=0))
print("------------------------------------")

print("最大值：",np.max(b1, axis=0))
print("最小值：",np.min(b1, axis=0))

print("差距：",np.ptp(b1, axis=0))

垂直加總： [12 15 18 21]
橫向加總： [ 6 22 38]
------------------------------------
加總： [12 15 18 21]
平均： [4. 5. 6. 7.]
中位數： [4. 5. 6. 7.]
變異數： [10.66666667 10.66666667 10.66666667 10.66666667]
標準差： [3.26598632 3.26598632 3.26598632 3.26598632]
------------------------------------
最大值： [ 8  9 10 11]
最小值： [0 1 2 3]
差距： [8 8 8 8]


## 數學函數

In [40]:
#x0 = [1.234, 5.5558, 9.0]#5.5678
#print(round(x0[1], 0))

x1 = np.array([1.234, 5.5678, 9.0])
R = np.round (x1)
print(R)

F = np.trunc(x1)
print(F)

[1. 6. 9.]
[1. 5. 9.]


In [41]:
x2 = np.array([1,2,3])

e1 = np.log2(x2)
print(e1)

e2 = np.log(x2)#loge, e=2.71828
print(e2)

e3 = np.log10(x2)
print(e3)

[0.        1.        1.5849625]
[0.         0.69314718 1.09861229]
[0.         0.30103    0.47712125]


## 方程式求解

In [42]:
from sympy.solvers import solve
from sympy import Symbol

ModuleNotFoundError: No module named 'sympy'

In [ ]:
x = Symbol('x')
print(solve(x**3-1, x))

In [ ]:
x1 = Symbol('x1')
y1 = Symbol('y1')

print(solve([x1+y1-5, x1-y1-1], x1,y1))

In [ ]:
print(((x+2)*4+3*(x-2)).subs(x, 2))