# Dealing with missing data

In [1]:
import pandas as pd
from io import StringIO
import sys

csv_data = \
'''A,B,C,D
1.0,2.0,3.0,4.0
5.0,6.0,,8.0
10.0,11.0,12.0,'''

# If you are using Python 2.7, you need
# to convert the string to unicode:

if (sys.version_info < (3, 0)):
    csv_data = unicode(csv_data)

df = pd.read_csv(StringIO(csv_data))
df

A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   NaN  8.0
2  10.0  11.0  12.0  NaN

In [2]:
df.isnull().sum()

A    0
B    0
C    1
D    1
dtype: int64

In [3]:
# access the underlying NumPy array
# via the `values` attribute
df.values

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6., nan,  8.],
       [10., 11., 12., nan]])

In [4]:
# remove rows that contain missing values

df.dropna(axis=0)

A    B    C    D
0  1.0  2.0  3.0  4.0

In [5]:
# remove columns that contain missing values

df.dropna(axis=1)

A     B
0   1.0   2.0
1   5.0   6.0
2  10.0  11.0

In [6]:
# remove columns that contain missing values

df.dropna(axis=1)

A     B
0   1.0   2.0
1   5.0   6.0
2  10.0  11.0

In [7]:
# only drop rows where all columns are NaN

df.dropna(how='all')  

A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   NaN  8.0
2  10.0  11.0  12.0  NaN

In [8]:
# drop rows that have fewer than 3 real values 

df.dropna(thresh=4)

A    B    C    D
0  1.0  2.0  3.0  4.0

In [9]:
# only drop rows where NaN appear in specific columns (here: 'C')

df.dropna(subset=['C'])

A     B     C    D
0   1.0   2.0   3.0  4.0
2  10.0  11.0  12.0  NaN

## Imputing missing values

In [10]:
# again: our original array
df.values

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6., nan,  8.],
       [10., 11., 12., nan]])

In [11]:
# impute missing values via the column mean

from sklearn.impute import SimpleImputer
import numpy as np

imr = SimpleImputer(missing_values=np.nan, strategy='mean')
imr = imr.fit(df.values)
imputed_data = imr.transform(df.values)
imputed_data

array([[ 1. ,  2. ,  3. ,  4. ],
       [ 5. ,  6. ,  7.5,  8. ],
       [10. , 11. , 12. ,  6. ]])

<br>
<br>

In [12]:
df.fillna(df.mean())

A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   7.5  8.0
2  10.0  11.0  12.0  6.0

# Handling categorical data

## Nominal and ordinal features
## 機器學習比較常用模型
## 深度學習才會常用文字轉數字的程式

In [13]:
import pandas as pd
# create a sample dataframe 
df = pd.DataFrame([['green', 'M', 10.1, 'class2'],
                   ['red', 'L', 13.5, 'class1'],
                   ['blue', 'XL', 15.3, 'class2']])

df.columns = ['color', 'size', 'price', 'classlabel']
df

color size  price classlabel
0  green    M   10.1     class2
1    red    L   13.5     class1
2   blue   XL   15.3     class2

<br>
<br>

## Mapping ordinal features

In [14]:
size_mapping = {'XL': 3,
                'L': 2,
                'M': 1}
# 文字轉數字, key is the original value, value is the new value
# map the values in the 'size' column
# to integers using the size_mapping dictionary 

df['size'] = df['size'].map(size_mapping)
df

color  size  price classlabel
0  green     1   10.1     class2
1    red     2   13.5     class1
2   blue     3   15.3     class2

In [15]:
inv_size_mapping = {v: k for k, v in size_mapping.items()} # invert the mapping
# 上面這段重點是程式語法的撰寫
# v is value, k is key
# 上面程式是K:V to V:K

df['size'].map(inv_size_mapping) # map the integers back to the original values

0     M
1     L
2    XL
Name: size, dtype: object

<br>
<br>

## Encoding class labels

In [16]:
import numpy as np

# create a mapping dict
# to convert class labels from strings to integers
class_mapping = {label: idx for idx, label in enumerate(np.unique(df['classlabel']))}
# 從classlabel欄位刪除重複值(unique),並排序後,用enumerate編號
# 
class_mapping

df

color  size  price classlabel
0  green     1   10.1     class2
1    red     2   13.5     class1
2   blue     3   15.3     class2

In [17]:
# to convert class labels from strings to integers
df['classlabel'] = df['classlabel'].map(class_mapping)
df

color  size  price  classlabel
0  green     1   10.1           1
1    red     2   13.5           0
2   blue     3   15.3           1

In [18]:
# reverse the class label mapping
inv_class_mapping = {v: k for k, v in class_mapping.items()}
df['classlabel'] = df['classlabel'].map(inv_class_mapping)
df

color  size  price classlabel
0  green     1   10.1     class2
1    red     2   13.5     class1
2   blue     3   15.3     class2

In [19]:
# 使用sklearn模型的寫法

from sklearn.preprocessing import LabelEncoder

# Label encoding with sklearn's LabelEncoder
class_le = LabelEncoder()
y = class_le.fit_transform(df['classlabel'].values)
y

array([1, 0, 1])

In [20]:
# reverse mapping
class_le.inverse_transform(y)

array(['class2', 'class1', 'class2'], dtype=object)

<br>
<br>

## Performing one-hot encoding on nominal features

In [21]:
X = df[['color', 'size', 'price']].values # 設定大X為資料表,包含3個欄位

color_le = LabelEncoder() #  
X[:, 0] = color_le.fit_transform(X[:, 0]) # 將colume 0(color)資料計算後回填回資料表
X


array([[1, 1, 10.1],
       [2, 2, 13.5],
       [0, 3, 15.3]], dtype=object)

In [22]:
from sklearn.preprocessing import OneHotEncoder # 
# OneHotEncoder 是將指定欄位的內容分成2進制表示,0或是1

X = df[['color', 'size', 'price']].values # 
color_ohe = OneHotEncoder() #color_ohe 採用OneHotEncoder

# color_ohe.fit_transform(X[:, 0].reshape(-1, 1))

color_ohe.fit_transform(X[:, 0].reshape(-1, 1)).toarray() # .toarray()是把資料展開成矩陣呈現

# X[:, 0].reshape(-1, 1) 是把X的第0欄資料(也就是color欄)轉成矩陣

# color_ohe.categories_ # categories_ 是把欄位的內容列出來

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [23]:
from sklearn.compose import ColumnTransformer
# 
X = df[['color', 'size', 'price']].values
c_transf = ColumnTransformer([ ('onehot', OneHotEncoder(), [0]),
                               ('nothing', 'passthrough', [1, 2])])
# columnTransformer 是將指定欄位做指定的轉換,這裡是把colume 0 做OneHotEncoder轉換, colume 1,2 不變
c_transf.fit_transform(X).astype(float) # .astype(float) 是把資料轉成float格式

array([[ 0. ,  1. ,  0. ,  1. , 10.1],
       [ 0. ,  0. ,  1. ,  2. , 13.5],
       [ 1. ,  0. ,  0. ,  3. , 15.3]])

In [24]:
# one-hot encoding via pandas

pd.get_dummies(df[['price', 'color', 'size']]) 
# get_dummies 是將指定欄位的內容分成2進制表示,0或是1

price  size  color_blue  color_green  color_red
0   10.1     1       False         True      False
1   13.5     2       False        False       True
2   15.3     3        True        False      False

In [25]:
# multicollinearity guard in get_dummies

pd.get_dummies(df[['price', 'color', 'size']], drop_first=True) 
# drop_first=True 是避免多重共線性,會把每個欄位的第一個值拿掉

price  size  color_green  color_red
0   10.1     1         True      False
1   13.5     2        False       True
2   15.3     3        False      False

In [26]:
# multicollinearity guard for the OneHotEncoder

color_ohe = OneHotEncoder(categories='auto', drop='first') 
# Categories='auto' 是自動偵測欄位的值, drop='first' 是避免多重共線性,會把每個欄位的第一個值拿掉
c_transf = ColumnTransformer([ ('onehot', color_ohe, [0]),
                               ('nothing', 'passthrough', [1, 2])]) 
# ColumnTransformer 是將指定欄位做指定的轉換,這裡是把colume 0 做OneHotEncoder轉換, colume 1,2 不變
c_transf.fit_transform(X).astype(float)

array([[ 1. ,  0. ,  1. , 10.1],
       [ 0. ,  1. ,  2. , 13.5],
       [ 0. ,  0. ,  3. , 15.3]])

<br>
<br>

## Optional: Encoding Ordinal Features

In [27]:
df = pd.DataFrame([['green', 'M', 10.1, 'class2'],
                   ['red', 'L', 13.5, 'class1'],
                   ['blue', 'XL', 15.3, 'class2']])

df.columns = ['color', 'size', 'price', 'classlabel']
df

color size  price classlabel
0  green    M   10.1     class2
1    red    L   13.5     class1
2   blue   XL   15.3     class2

In [28]:
df['x > M'] = df['size'].apply(lambda x: 1 if x in {'L', 'XL'} else 0) # apply是對欄位的每個值做運算
# 新增一個欄位,名稱為x > M, 內容是根據size欄位的值,如果是L或XL就填1,否則填0
df['x > L'] = df['size'].apply(lambda x: 1 if x == 'XL' else 0) # lambda是匿名函數
# 新增一個欄位,名稱為x > L, 內容是根據size欄位的值,如果是XL就填1,否則填0
del df['size'] # 刪除size欄位
df

color  price classlabel  x > M  x > L
0  green   10.1     class2      0      0
1    red   13.5     class1      1      0
2   blue   15.3     class2      1      1