In [6]:
from sklearn import datasets
from sklearn.neighbors import KNeighborsClassifier
import numpy as np

np.random.seed(0)

iris=datasets.load_iris()

In [7]:
iris_x=iris.data
iris_y=iris.target

# import pandas as pd
# iris_x = pd.DataFrame(iris.data)
# iris_x=iris_x.iloc[:, :2]

In [8]:
#permutation接收一個數作為參數(150),產生一個0-149的一維陣列並隨機打亂
indices = np.random.permutation(len(iris_x))

iris_x_train = iris_x[indices[:-10]]#隨機選取140個樣本
iris_y_train = iris_y[indices[:-10]]#取得140個樣本的標籤

iris_x_test = iris_x[indices[-10:]]#測試資料集
iris_y_test = iris_y[indices[-10:]]#測試資料集的標籤


In [9]:
KNeighborsClassifier?

Init signature:
KNeighborsClassifier(
    n_neighbors=5,
    *,
    weights='uniform',
    algorithm='auto',
    leaf_size=30,
    p=2,
    metric='minkowski',
    metric_params=None,
    n_jobs=None,
)
Docstring:     
Classifier implementing the k-nearest neighbors vote.

Read more in the :ref:`User Guide <classification>`.

Parameters
----------
n_neighbors : int, default=5
    Number of neighbors to use by default for :meth:`kneighbors` queries.

weights : {'uniform', 'distance'}, callable or None, default='uniform'
    Weight function used in prediction.  Possible values:

    - 'uniform' : uniform weights.  All points in each neighborhood
      are weighted equally.
    - 'distance' : weight points by the inverse of their distance.
      in this case, closer neighbors of a query point will have a
      greater influence than neighbors which are further away.
    - [callable] : a user-defined function which accepts an
      array of distances, and returns an array of the same shape

In [ ]:
#預設參數：n_neighbors=5， p=2(歐氏距離)/(p=1:曼哈頓距離)
knn = KNeighborsClassifier(p=2, n_neighbors=5, weights='distance') # k=5

knn.fit(iris_x_train, iris_y_train)

iris_y_predict = knn.predict(iris_x_test)
probility=knn.predict_proba(iris_x_test)

neighborpoint=knn.kneighbors(iris_x_test,5,False)#
score=knn.score(iris_x_test,iris_y_test,sample_weight=None)

print('iris_y_predict = ',iris_y_predict)
print('iris_y_test = ', iris_y_test)
print('score:',score)
print('probility:',probility)

iris_y_predict =  [1 2 1 0 0 0 2 1 2 0]
iris_y_test =  [1 1 1 0 0 0 2 1 2 0]
score: 0.9
probility: [[0.         1.         0.        ]
 [0.         0.29791809 0.70208191]
 [0.         1.         0.        ]
 [1.         0.         0.        ]
 [1.         0.         0.        ]
 [1.         0.         0.        ]
 [0.         0.         1.        ]
 [0.         1.         0.        ]
 [0.         0.         1.        ]
 [1.         0.         0.        ]]


In [11]:
print('Accuracy:', score)
print('測試點最近的鄰居index:', neighborpoint)


Accuracy: 0.9
測試點最近的鄰居index: [[ 71  81 127  63  38]
 [119  33  76  60  52]
 [ 79 132   1  13  27]
 [ 44 113 107  68  32]
 [122  87  99  97  68]
 [106  93  61  82 134]
 [ 46  30  86  70  34]
 [ 39 128 127  50  63]
 [116 104  80  51 121]
 [ 75  41  96  78 123]]
