In [ ]:
from sklearn import datasets
from sklearn.neighbors import KNeighborsClassifier # 載入KNN分類器
from sklearn.model_selection import train_test_split # 載入資料分割模組
from sklearn.metrics import accuracy_score # 載入準確率計算模組
import numpy as np

np.random.seed(0) # 設定隨機種子

iris=datasets.load_iris() # 載入鳶尾花資料集

In [2]:
iris_x=iris.data
iris_y=iris.target

# import pandas as pd
# iris_x = pd.DataFrame(iris.data)
# iris_x=iris_x.iloc[:, :2]

## 資料分割
手動切割資料的程式撰寫方式


In [3]:
#permutation接收一個數作為參數(150),產生一個0-149的一維陣列並隨機打亂
indices = np.random.permutation(len(iris_x))

iris_x_train = iris_x[indices[:-10]]#隨機選取140個樣本,:-10表示從頭到倒數第10個(不包含倒數第10個)
iris_y_train = iris_y[indices[:-10]]#取得140個樣本的標籤

iris_x_test = iris_x[indices[-10:]]#測試資料集,選取最後10個樣本
iris_y_test = iris_y[indices[-10:]]#測試資料集的標籤,最後10個樣本的標籤


In [8]:
KNeighborsClassifier? # 查看說明

SyntaxError: invalid syntax (3434432122.py, line 1)

In [ ]:
#預設參數：n_neighbors=5， p=2(歐氏距離)/(p=1:曼哈頓距離)
knn = KNeighborsClassifier(p=2, n_neighbors=5, weights='distance') # k=5

knn.fit(iris_x_train, iris_y_train)

iris_y_predict = knn.predict(iris_x_test) # 預測,返回預測標籤,knn.predict(X)返回的是類別標籤
probility=knn.predict_proba(iris_x_test) # 預測各類別的機率,返回各類別的機率,knn.predict_proba(X)返回的是各類別的機率
#  knn.kneighbors(X, n_neighbors=5, return_distance=True)返回距離和索引
#  1. return_distance=True返回距離和索引
#  2. return_distance=False返回索引
#  3. n_neighbors:鄰居數
#  4. X:測試資料集
#  5. kneighbors返回的是距離和索引


neighborpoint=knn.kneighbors(iris_x_test,5,False)# 返回鄰居點的索引
score=knn.score(iris_x_test,iris_y_test,sample_weight=None)

print('iris_y_predict = ',iris_y_predict) # 預測標籤
print('iris_y_test = ', iris_y_test) # 測試標籤
print('score:',score)
print('probility:',probility) # 各類別的機率
print('neighborpoint:',neighborpoint) # 鄰居點的索引

iris_y_predict =  [1 2 1 0 0 0 2 1 2 0]
iris_y_test =  [1 1 1 0 0 0 2 1 2 0]
score: 0.9
probility: [[0.         1.         0.        ]
 [0.         0.29791809 0.70208191]
 [0.         1.         0.        ]
 [1.         0.         0.        ]
 [1.         0.         0.        ]
 [1.         0.         0.        ]
 [0.         0.         1.        ]
 [0.         1.         0.        ]
 [0.         0.         1.        ]
 [1.         0.         0.        ]]
neighborpoint: [[ 71  81 127  63  38]
 [119  33  76  60  52]
 [ 79 132   1  13  27]
 [ 44 113 107  68  32]
 [122  87  99  97  68]
 [106  93  61  82 134]
 [ 46  30  86  70  34]
 [ 39 128 127  50  63]
 [116 104  80  51 121]
 [ 75  41  96  78 123]]


第2筆資料預測錯誤

修改K值為1,11,第二筆資料還是錯誤,可能是原始測試資料分類就錯誤

In [10]:
print('Accuracy:', score)
print('測試點最近的鄰居index:', neighborpoint)


Accuracy: 0.9
測試點最近的鄰居index: [[ 71  81 127  63  38]
 [119  33  76  60  52]
 [ 79 132   1  13  27]
 [ 44 113 107  68  32]
 [122  87  99  97  68]
 [106  93  61  82 134]
 [ 46  30  86  70  34]
 [ 39 128 127  50  63]
 [116 104  80  51 121]
 [ 75  41  96  78 123]]


測試資料第二筆是錯誤

使用下面程式列印出資料內容

丟到KNN_iris.ipynb (使用sklearn模型)

驗證測試結果-2025.10.10

In [11]:
print(iris_x_test[1]) # 測試資料集的第二個樣本
print(iris_x_train[neighborpoint[1]]) # 測試資料集的第二個樣本的鄰居點
print(iris_y_train[neighborpoint[1]]) # 測試資料集的第二個樣本的鄰居點的標籤
print(iris_y_train) # 訓練資料集的標籤

[5.9 3.2 4.8 1.8]
[[6.  3.  4.8 1.8]
 [6.1 3.  4.9 1.8]
 [5.9 3.  5.1 1.8]
 [6.  3.4 4.5 1.6]
 [6.3 3.3 4.7 1.6]]
[2 2 2 1 1]
[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 1 1 1 2 0 2 0 0 1 2 2 2 2 1 2 1 1 2 2 2 2 1 2 1 0 2 1 1 1 1 2 0 0 2 1 0 0
 1 0 2 1 0 1 2 1 0 2 2 2 2 0 0 2 2 0 2 0 2 2 0 0 2 0 0 0 1 2 2 0 0 0 1 1 0
 0 1 0 2 1 2 1 0 2 0 2 0 0 2 0 2 1 1 1 2 2 1 1 0 1 2 2 0 1]
