# 以Scikit-learn SVM進行鳶尾花(Iris)品種的辨識

## 載入相關套件

In [1]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np

## 載入資料集

In [2]:
X, y = datasets.load_iris(return_X_y=True)

## 資料分割

In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2)

## 特徵縮放

In [4]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_std = scaler.fit_transform(X_train)
X_test_std = scaler.transform(X_test)

## 模型訓練

In [5]:
from sklearn.svm import SVC

clf = SVC(probability=True, kernel='rbf')
clf.fit(X_train_std, y_train)

SVC(probability=True)

## 模型評分

In [6]:
# 計算準確率
y_pred = clf.predict(X_test_std)
print(clf.score(X_test_std, y_test))
print(f'{accuracy_score(y_test, y_pred)*100:.2f}%') 

0.9333333333333333
93.33%


In [13]:
clf.support_vectors_

array([[-0.21465262,  3.18420425, -1.36469354, -1.1042524 ],
       [-1.63907555, -1.70263784, -1.4796958 , -1.23597237],
       [-1.75777746, -0.30639724, -1.42219467, -1.36769234],
       [-1.87647937, -0.07369048, -1.59469807, -1.49941231],
       [-1.52037364,  1.32255012, -1.6521992 , -1.36769234],
       [-0.57075835,  0.85713659, -1.36469354, -1.1042524 ],
       [-1.75777746,  0.39172306, -1.4796958 , -1.36769234],
       [-0.92686409,  1.78796365, -1.13468901, -1.1042524 ],
       [-1.045566  , -0.07369048, -1.30719241, -1.36769234],
       [ 0.37885693, -1.93534461,  0.36034043,  0.34466725],
       [ 1.32847222,  0.39172306,  0.47534269,  0.21294728],
       [-1.045566  , -1.70263784, -0.32967316, -0.31393259],
       [ 0.97236649,  0.15901629,  0.47534269,  0.34466725],
       [-0.33335453, -0.30639724, -0.15716976,  0.08122731],
       [ 0.0227512 ,  0.39172306,  0.53284383,  0.73982716],
       [-0.45205644, -1.70263784,  0.07283477,  0.08122731],
       [ 0.14145311, -0.

In [8]:
len(clf.support_vectors_)

47

In [9]:
clf.support_

array([ 20,  32,  49,  52,  53,  77,  81, 111, 113,   1,   6,   8,  10,
        11,  17,  29,  42,  46,  47,  48,  50,  56,  57,  60,  64,  68,
        73,  86,  90, 110,   3,   7,  15,  19,  21,  25,  31,  39,  74,
        76,  80,  85,  91,  92,  99, 106, 117])

In [16]:
#clf.predict_proba(X_test)
clf.predict(X_test)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2])

In [11]:
clf.predict_log_proba(X_test)

array([[-1.17608549, -1.33273185, -0.84919224],
       [-1.27294905, -1.43555587, -0.72978563],
       [-1.17601786, -1.33266019, -0.8492852 ],
       [-1.17717228, -1.33388491, -0.84769946],
       [-1.19548281, -1.35325318, -0.82315591],
       [-1.27831672, -1.43893576, -0.72502131],
       [-1.24239034, -1.40275356, -0.76488423],
       [-1.23389081, -1.3937045 , -0.77503392],
       [-1.17710028, -1.33381605, -0.8477936 ],
       [-1.26825088, -1.4329736 , -0.73380592],
       [-1.17781856, -1.33458606, -0.8468041 ],
       [-1.18388316, -1.34112203, -0.83849642],
       [-1.22749242, -1.38697776, -0.78275608],
       [-1.17688915, -1.33358191, -0.84808958],
       [-1.17821207, -1.33496555, -0.84628872],
       [-1.17640282, -1.33306928, -0.84875549],
       [-1.45002963, -1.6094133 , -0.5701657 ],
       [-1.29231365, -1.45598695, -0.70887982],
       [-1.27304939, -1.43574707, -0.72963297],
       [-1.26496606, -1.42536914, -0.73954422],
       [-1.2537753 , -1.41409837, -0.751

In [12]:
clf.predict_proba(X_test)

array([[0.30848394, 0.26375574, 0.42776032],
       [0.28000465, 0.23798304, 0.48201231],
       [0.30850481, 0.26377464, 0.42772056],
       [0.30814887, 0.26345178, 0.42839935],
       [0.30255784, 0.25839828, 0.43904388],
       [0.27850571, 0.23718004, 0.48431425],
       [0.28869332, 0.24591888, 0.4653878 ],
       [0.29115753, 0.24815431, 0.46068815],
       [0.30817105, 0.26346993, 0.42835902],
       [0.28132326, 0.23859837, 0.48007837],
       [0.30794978, 0.26326713, 0.42878309],
       [0.30608784, 0.26155204, 0.43236012],
       [0.29302644, 0.24982921, 0.45714435],
       [0.30823612, 0.26353162, 0.42823225],
       [0.30782862, 0.26316724, 0.42900414],
       [0.30838607, 0.26366675, 0.42794718],
       [0.23456334, 0.20000492, 0.56543174],
       [0.27463464, 0.23317012, 0.49219524],
       [0.27997656, 0.23793754, 0.4820859 ],
       [0.28224888, 0.2404197 , 0.47733142],
       [0.2854252 , 0.24314474, 0.47143006],
       [0.30826006, 0.26355125, 0.42818869],
       [0.