# 以Scikit-learn SVM進行鳶尾花(Iris)品種的辨識

## 載入相關套件

In [1]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np

## 載入資料集

In [ ]:
X, y = datasets.load_iris(return_X_y=True) # 載入鳶尾花資料集

## 資料分割

In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2)

## 特徵縮放

In [4]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_std = scaler.fit_transform(X_train)
X_test_std = scaler.transform(X_test)

## 模型訓練

In [ ]:
from sklearn.svm import SVC # sklearn.svm 

clf = SVC(probability=True, kernel='rbf') # svc(probability = True, kernel = 'rbf')
clf.fit(X_train_std, y_train)

SVC(probability=True)

## 模型評分

In [ ]:
# 計算準確率
y_pred = clf.predict(X_test_std) # clf.predict()
print(clf.score(X_test_std, y_test))
print(f'{accuracy_score(y_test, y_pred)*100:.2f}%') 

0.9666666666666667
96.67%


In [ ]:
clf.support_vectors_ # 

array([[-1.71957302, -0.40748675, -1.31576298, -1.29788824],
       [-0.98697386, -0.17898951, -1.20114116, -1.29788824],
       [-0.49857442,  0.73499947, -1.25845207, -1.03256185],
       [-0.13227485,  3.01997191, -1.25845207, -1.03256185],
       [-0.13227485,  1.64898844, -1.14383025, -1.16522505],
       [-0.864874  ,  0.50650222, -1.14383025, -0.89989866],
       [-1.4753733 ,  1.19199396, -1.54500662, -1.29788824],
       [-0.864874  , -1.32147573, -0.39878842, -0.1039195 ],
       [ 1.2108236 , -0.635984  ,  0.63280797,  0.29407008],
       [ 0.23402473, -2.00696746,  0.17432069, -0.23658269],
       [-0.37647457, -1.77847021,  0.17432069,  0.16140689],
       [-0.25437471, -0.17898951,  0.46087524,  0.42673327],
       [-0.37647457, -1.32147573,  0.17432069,  0.16140689],
       [ 0.23402473,  0.73499947,  0.46087524,  0.55939647],
       [ 0.84452403, -0.635984  ,  0.51818615,  0.42673327],
       [-0.37647457, -1.09297848,  0.40356433,  0.02874369],
       [-1.10907372, -1.

In [ ]:
len(clf.support_vectors_) # len()

42

In [ ]:
clf.support_ # 

array([ 21,  35,  47,  52,  81, 107, 116,   8,  22,  23,  24,  29,  48,
        51,  54,  67,  71,  74,  75,  87,  90, 112, 113, 115,  10,  14,
        17,  18,  27,  30,  31,  33,  44,  53,  55,  61,  77,  78,  92,
        96,  99, 110], dtype=int32)

In [10]:
#clf.predict_proba(X_test)
clf.predict(X_test)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2])

In [11]:
clf.predict_log_proba(X_test)

array([[-1.17608549, -1.33273185, -0.84919224],
       [-1.27294905, -1.43555587, -0.72978563],
       [-1.17601786, -1.33266019, -0.8492852 ],
       [-1.17717228, -1.33388491, -0.84769946],
       [-1.19548281, -1.35325318, -0.82315591],
       [-1.27831672, -1.43893576, -0.72502131],
       [-1.24239034, -1.40275356, -0.76488423],
       [-1.23389081, -1.3937045 , -0.77503392],
       [-1.17710028, -1.33381605, -0.8477936 ],
       [-1.26825088, -1.4329736 , -0.73380592],
       [-1.17781856, -1.33458606, -0.8468041 ],
       [-1.18388316, -1.34112203, -0.83849642],
       [-1.22749242, -1.38697776, -0.78275608],
       [-1.17688915, -1.33358191, -0.84808958],
       [-1.17821207, -1.33496555, -0.84628872],
       [-1.17640282, -1.33306928, -0.84875549],
       [-1.45002963, -1.6094133 , -0.5701657 ],
       [-1.29231365, -1.45598695, -0.70887982],
       [-1.27304939, -1.43574707, -0.72963297],
       [-1.26496606, -1.42536914, -0.73954422],
       [-1.2537753 , -1.41409837, -0.751

In [12]:
clf.predict_proba(X_test)

array([[0.30848394, 0.26375574, 0.42776032],
       [0.28000465, 0.23798304, 0.48201231],
       [0.30850481, 0.26377464, 0.42772056],
       [0.30814887, 0.26345178, 0.42839935],
       [0.30255784, 0.25839828, 0.43904388],
       [0.27850571, 0.23718004, 0.48431425],
       [0.28869332, 0.24591888, 0.4653878 ],
       [0.29115753, 0.24815431, 0.46068815],
       [0.30817105, 0.26346993, 0.42835902],
       [0.28132326, 0.23859837, 0.48007837],
       [0.30794978, 0.26326713, 0.42878309],
       [0.30608784, 0.26155204, 0.43236012],
       [0.29302644, 0.24982921, 0.45714435],
       [0.30823612, 0.26353162, 0.42823225],
       [0.30782862, 0.26316724, 0.42900414],
       [0.30838607, 0.26366675, 0.42794718],
       [0.23456334, 0.20000492, 0.56543174],
       [0.27463464, 0.23317012, 0.49219524],
       [0.27997656, 0.23793754, 0.4820859 ],
       [0.28224888, 0.2404197 , 0.47733142],
       [0.2854252 , 0.24314474, 0.47143006],
       [0.30826006, 0.26355125, 0.42818869],
       [0.